### ISSUE TITLE
Allow exclusion of subfolders from sync

### ISSUE THREAD

**Issue by SamSchott** [SamSchott/maestral-dropbox#1]
At the moment only top level folders can be excluded from syncing.

**Comment by bbaserdem** [comment]
Is this feature planned any time soon? Pretty much only thing I am missing from the official client at the moment.

**Comment by SamSchott** [comment]
The changes in the sync code have already been made in the development branch, but they will still need some testing. Also, implementing the UI is a bit tedious. But I will get to it eventually.

It's planned for v0.3.3, but it may still be month until its released.

**Comment by SamSchott** [comment]
Done in v0.4.0.

**Comment by sahilseth** [comment]
how do we specify subfolders? I tried a few variations but did not work.
folder to exclude: `~/Dropbox/foo/.bar`

I tried:
```
maestral excluded add ~/Dropbox/foo/.bar
maestral excluded add /foo/.bar
maestral excluded add foo/.bar
```
Error: Cannot exlcude item: "/foo/.bar" does not exist on Dropbox

If the folder name is `bar` instead of `.bar` it gets stuck without an error, will update it if it returns and error later.

**Comment by SamSchott** [comment]
The last commands should work if there is indeed a folder `/foo/.bar` in your Dropbox and there should be no difference between “hidden” items which start with a period and regular ones. Are you sure that the folder is on the remote Dropbox? You can list the content of `/foo` with `maestral ls /foo`.
