### ISSUE TITLE
Archiecture questions

### ISSUE THREAD

**Issue by peterhoeg** [SamSchott/maestral-dropbox#47]
This isn't a bug report but more of a discussion thing. If this isn't the right forum, please let me know.

It's currently possible to run maestral in a few different ways:

 - maestral sync in a terminal
 - maestral daemon start in a terminal but backgrounded
 - maestral gui
 - maestral sync or daemon start in a systemd unit (probably via launchd too on darwin)
 
 When run in daemon mode, it's possible to interact with the daemon, ie: maestral daemon errors
 
 In GUI mode that's possible too but not when run in "sync" mode.
 
 How about splitting up the application, so you have a few different components:
 
 a. The sync engine that runs headlessly 
 b. A UI that could either be the current GUI that doesn't do any syncing on its own or a CLI UI
 
If launching the GUI without the "engine" running, it could be spawned. One application that does it this way is deluge (bittorrent application).

**Comment by SamSchott** [comment]
@peterhoeg, you bring up a valid point. I expect that the 0.3 release will be all about sorting the existing functionality and ironing out bugs. Here is an overview of the current structure. Do let me know if you have any ideas to simplify this.

### Launch options

#### Interactive
Launch a Python interpreter and run:
```python
from maestral.main import Maestral
m = Maestral()
```

#### maestral sync
Does exactly the above. Additionally, `maestral sync` creates a server at 'localhost' with an event loop. The server accepts remote calls of selected methods and returns their results (as pickled objects). **You should be able to interact with this session through the `maestral daemon` commands.** To quit, you need to abort the event loop in the console with Ctrl-C or by calling `maestral daemon stop` in a different console.

This is the preferred method for launching maestral as a command-line client with systemd or launchd. I have removed the `maestral autostart` command for now, since it used to register the GUI script with launchd or as a Gnome desktop entry and had no effect on the command-line version.

#### maestral daemon start
Does exactly the above, but spawns a new process. It also redirects all stdin / stdout / stderr to DEVNULL so that the process remains silent. You will need to investigate the logs to see the output.

#### maestral gui
Starts a GUI which creates an instance of `maestral.main.Maestral` and calls its methods. At the moment, the GUI provides more functionality than the command line scripts because it can call methods of `Maestral` which are not currently exposed on the server. It will need some work to reach feature parity, but I have started. Eventually, the GUI should be able to perform of all of its functions through exposed methods, at which point it will no longer need direct access to the Maestral instance. One can then decouple the two and launch them independently.

### Module structure

At the moment, the above functionality is structured into modules follows: the sync engine is contained in all the top-level modules, except for `console_script`. The GUI is located at`maestral.gui` and is fully self-contained. `console_script` currently contains both the CLI UI, as well as the logic to create and interact with the daemon / server (this uses the excellent Pyro4 package).

As a side note, the current 0.3.2-dev version prevents multiple `Maestral` instances that sync to the same folder from running concurrently. Calls to `maestral sync`, `maestral daemon start` or `maestral gui` with the same configuration profile will return with an error message.

### Plans

- Expose all methods required by the GUI through the server.
- Allow the GUI to attach to a running daemon.
- I might consider removing the `maestral sync` command if it is confusing. It could be provided as a flag to the daemon instead, such as `maestral daemon start --join`.
- I may add `maestral daemon autostart` in the future, but this will require supporting different platforms.

**Comment by peterhoeg** [comment]
>  Launch options
>    Interactive
>    maestral sync
>    maestral daemon start

So my understanding is, that these 3 all act the same way (fork vs non-fork doesn't really matter) as a server process that currently can be controlled by the cli, correct?

>    maestral gui
>   Eventually, the GUI should be able to perform of all of its functions through exposed methods

Both cli and gui control of the server process should have feature parity, correct?

>  Plans
>
>     * Expose all methods required by the GUI through the server.
>     * Allow the GUI to attach to a running daemon.

This makes perfect sense.

>     * I might consider removing the maestral sync command if it is
>       confusing. It could be provided as a flag to the daemon instead, such
>       as maestral daemon start --join.

The way I see it, there really should be 2 ways to launch the server process:

1. in the foreground
2. forking and running the background

Whether that's "maestral sync" or "maestral daemon start --foreground" really doesn't matter.

>     * I may add maestral daemon autostart in the future, but this will
>       require supporting different platforms.

Got it.

**Comment by peterhoeg** [comment]
I guess we can close this with 0.4.0.
