### ISSUE TITLE
[BUG] Maestral hanging after setup

### ISSUE THREAD

**Issue by tlonic** [SamSchott/maestral-dropbox#57]
**Describe the bug**
Maestral hangs after set up.
**To Reproduce**
Steps to reproduce the behaviour.

1. Install maestral-0.4.0 via `pip install --user maestral`
2. run `maestral gui`, get token, enter
3. set up sync location
4. finish

**Expected behaviour**

Maestral should start syncing data. Instead, it hangs.

> 2019-09-25 23:31:27 maestral.sync.monitor WARNING: Maestral index could not be found.

is printed to the console.

If you kill maestral after setting up via `maestral gui` and start it via `maestral start`, the same issue occurs.

**System (please complete the following information):**
 - Maestral version: 0.4.0
 - OS: ArchLinux
 - Desktop environment: xmonad + gnome
 - Qt version:  5.13.1

**Additional context**

strace on the `maestral start` process suggests it's hanging at creating/opening the pid file:

> stat("/home/username", {st_mode=S_IFDIR|0700, st_size=45056, ...}) = 0
> stat("/home/username", {st_mode=S_IFDIR|0700, st_size=45056, ...}) = 0
> mkdir("/home/username/.cache", 0777)      = -1 EEXIST (File exists)
> stat("/home/username/.cache", {st_mode=S_IFDIR|0755, st_size=4096, ...}) = 0
> stat("/run/user/1000", {st_mode=S_IFDIR|0700, st_size=300, ...}) = 0
> mkdir("/run/user/1000/maestral", 0777)  = -1 EEXIST (File exists)
> stat("/run/user/1000/maestral", {st_mode=S_IFDIR|0755, st_size=40, ...}) = 0
> openat(AT_FDCWD, "/run/user/1000/maestral/maestral.pid", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)

Creating this file manually doesn't change things, though the strace output is slightly different:

> fstat(17, {st_mode=S_IFREG|0644, st_size=0, ...}) = 0
> ioctl(17, TCGETS, 0x7ffd74cf2bf0)       = -1 ENOTTY (Inappropriate ioctl for device)
> lseek(17, 0, SEEK_CUR)                  = 0
> ioctl(17, TCGETS, 0x7ffd74cf2b20)       = -1 ENOTTY (Inappropriate ioctl for device)
> lseek(17, 0, SEEK_CUR)                  = 0
> fstat(17, {st_mode=S_IFREG|0644, st_size=0, ...}) = 0
> read(17, "", 8192)                      = 0
> close(17)                               = 0
> stat("/home/username", {st_mode=S_IFDIR|0700, st_size=45056, ...}) = 0
> stat("/home/username", {st_mode=S_IFDIR|0700, st_size=45056, ...}) = 0
> mkdir("/home/username/.cache", 0777)      = -1 EEXIST (File exists)
> stat("/home/username/.cache", {st_mode=S_IFDIR|0755, st_size=4096, ...}) = 0
> stat("/run/user/1000", {st_mode=S_IFDIR|0700, st_size=300, ...}) = 0
> mkdir("/run/user/1000/maestral", 0777)  = -1 EEXIST (File exists)
> stat("/run/user/1000/maestral", {st_mode=S_IFDIR|0755, st_size=60, ...}) = 0
> openat(AT_FDCWD, "/run/user/1000/maestral/maestral.pid", O_RDONLY|O_CLOEXEC) = 17

**Comment by SamSchott** [comment]
I agree, it looks like the PID file is not created when starting maestral. Can you start maestral in the foreground, by running `maestral start --foreground`, and see if this throws any Python errors?

If the above command runs successfully, it suggests that the PID file is created but cannot be found later. If this is the case, running `maestral status` from a second console should return "Maestral daemon is not running".

The warning message about the missing index is expected before the initial sync, it will be removed in the next release since it is somewhat misleading.

**Comment by tlonic** [comment]
Yes, `maestral status` does indicate that the daemon isn't running.

Strangely enough, I ran `maestral start --foreground` and it synced, but after stopping `maestral` and trying to run `maestral start` again, it seems my config has been wiped! It asks me for an auth token again, and `maestral account-info` says No Dropbox account linked.

**Comment by SamSchott** [comment]
Hm, that is a bit confusing. The PID file seems to be created successfully, otherwise `maestral start --foreground` would fail. The only issue I can think of is that a different directory is chosen for creating and reading the PID file (it should always be "$XDG_RUNTIME_DIR/maestral/maestral.pid").

Regarding the deletion of your config files, it is quite possible that you created multiple instances of maestral that were accessing the config in parallel. This should not happen when they can find the PID file... 

Could you install the development version of Maestral with `pip install -U --pre maestral` and see if you are still having problems? I have simplified the code which handles the PID file and it should be easier to debug now. After the installation, could you:

1) Log out and log in again to clear the runtime directory and delete the config directory at "~/.config/maestral".
2) Run `maestral start --foreground` for the first startup.
3) After completing the setup again, run `maestral status` from a different console and see if it can find the process.
4) If not, check if the PID file is created anywhere else than "/run/user/1000/maestral/maestral.pid".

Apologies for those issues!

**Comment by tlonic** [comment]
1. I ran `maestral start --foreground`, set everything up, and everything synced fine.
2.  Ran `maestral status` and it said it was running, 0 sync errors. maestral.pid was in my runtime folder. 
3. Ran `maestral stop` to stop the foreground process. 
4. Then, I ran `maestral start` to run the daemon. Same result -- `maestral status` says process not running, and maestral.pid is nowhere to be found.

**Comment by SamSchott** [comment]
Ok, thanks. And just to confirm, what does `maestral start` output? Does it just hang at "Starting Maestral..." or do you get an "[OK]" or "[FAILED]"?

One last check: after you run `maestral start`, do you get any log output? You can view the logs with `maestral log show` (and clear them with `maestral log clear`). I still suspect that maestral is started, but that the spawned subprocess does not write the PID file to the corrcet runtime dir.

**Comment by tlonic** [comment]
it hangs at "Starting Maestral..."

The only thing in the logs is this:

2019-09-26 22:44:36 maestral.sync.oauth DEBUG: Using keyring: keyring.backends.chainer.ChainerBackend (priority: 10)

**Comment by SamSchott** [comment]
I see now why it hangs: There is indeed a bug in the code which checks for correct startup. If it cannot find the pid of the subprocess, it should time out within 1 sec, but it did not.

However, I am still puzzled as to why maestral does not start. The code which is run when starting the daemon is the following:

```python
import subprocess

sp = subprocess.Popen(
    "maestral start --foreground -c {}".format("maestral"),
    shell=True,
)
```
I.e., it just runs `maestral start --foreground` in a subprocess! Could you try this manually? You can then get the PID of the subprocess with `sp.pid` and check is it actually running if `sp.wait(2)` raises a `TimeoutExpired` error.

**Comment by tlonic** [comment]
Running this code manually, sp.pid has a value, and the subprocess is running.

**Comment by SamSchott** [comment]
Thanks, that is a good sign. I have added a verbose option to `maestral start` now, which prints all log output to the console, and added logging to the daemon code. Could you install the latest development branch with `pip3 install -U git+https://github.com/samschott/maestral-dropbox@develop` and then run:

```shell
maestral log level DEBUG
maestral start -v
```

This should clearly show which part the startup fails.

**Comment by tlonic** [comment]
Aha:

> 2019-09-28 20:59:47 maestral.sync.oauth DEBUG: Using keyring: keyring.backends.SecretService.Keyring (priority: 5)
Starting Maestral.../bin/sh: maestral: command not found
2019-09-28 20:59:49 maestral.sync.daemon ERROR: Could not start Maestral daemon process
Starting Maestral...        [FAILED]

I installed Maestral as a user, and ~/.local/bin wasn't in the PATH for /bin/sh because I only put it in .bash_profile.

For some reason when I run the subprocess code in the interpreter, it used bash, which has ~/.local/bin in its path.

**Comment by SamSchott** [comment]
Ah, ok. Glad you found the issue! I had not foreseen the problem when passing `shell=True` to `subprocess.Popen`.

Thinking about it, `shell=True` really is not necessary and I will remove it for the next release. In that case, `Popen` will search for the `maestral` executable directly, using the PATH as it was when Python launched.
