### ISSUE TITLE
Suggestion: use standard Dropbox folder name, or allow to pick name

### ISSUE THREAD

**Issue by ahydronous** [SamSchott/maestral-dropbox#70]
I have several scripts that rely on my Dropbox folder just being named 'Dropbox'.
By having it named 'Dropbox (Maestral)' those scripts break.  

I could either use 'Dropbox (Maestral)', but that would break the script for normal Dropbox installations, or regex for Dropbox, but that introduces more complication into the script, and I might not be the only one who expects Maestral to use the default Dropbox name.  

My suggestion is to use either the normal Dropbox folder name, or give users the choice which name they want to use.

**Comment by SamSchott** [comment]
The default folder name "Dropbox (Maestral)" was chosen to avoid conflicts with possible Dropbox folders created by the official client. It is possible to set a custom folder name, just not through the GUI at the moment.

If you have installed the Python package instead of (or in addition to) the app bundle, you can run from the command line:
```shell
$ maestral set-dir
```
Maestral will prompt you for a new folder location (including the folder name!) and will then move your contents to the new location. This works even if Maestral is currently running.

**Comment by SamSchott** [comment]
BTW, the same holds when running Maestral's setup through the command line: you will be prompted to enter the full path of the Dropbox folder instead of its parent directory only.

The reason why I chose not do to this in the GUI: Users would have to either create the new folder themselves before selecting it, or the UI would need to provide a separate step / input box to provide the folder name. It seemed to niche of a use case for this extra step.

**Comment by ahydronous** [comment]
Cool, thanks for the clarification!

**Comment by cotfas** [comment]
On the mac version if I do not have the terminal compiled version, how can I change the name from 'Dropbox (Maestral)' to 'Dropbox'?
