### ISSUE TITLE
Feature request: option for notifications only on problems

### ISSUE THREAD

**Issue by coxackie** [SamSchott/maestral-dropbox#82]
I was wondering whether it would be able to fine-tune the "notifications" command by including an option to notify only on problems. What I have in mind basically is:
 - sync errors
 - connectivity issues (related to sync errors, but could just be internet connection problems)
 - failure to start the daemon.

 Let me give some background. I work with LaTeX a lot, which means building frequently (tex to pdf). When notifications are on, there is so much incoming that the Gnome notification area becomes a mess. I therefore tend to turn them off, and just use the system tray icon from gui to see whether syncing happens, and whether there are any sync errors. This is literally the only thing that I use it for - if there was a way to know if anything is wrong without having to look at the system tray icon, and get notified only when something goes wrong, I would have no need for GUI at all.

 I believe that this option could also benefit other users - if it is not too tough to implement, I would love to see it.

**System (please complete the following information):**
 - Maestral version: 0.5.2
 - OS: Arch
 - Desktop environment: Gnome 3.34

**Comment by SamSchott** [comment]
@coxackie, this should not be difficult to implement. I am planning to improve the desktop notification handling anyways.

For now, I have done the following (available in the pre-release channel):

* Notify only for remote changes and not for those which originated locally. This should significantly reduce the number of unwanted notifications - no one needs to be notified that a file has changed when they themselves *just* changed it. 
* Added notifications for logged errors: Serious errors such as revoked Dropbox access, deleted Dropbox folder, etc, are currently only shown in the GUI as alert windows or printed as red warnings when invoking any CLI command. Since notifications are handled by the daemon, this currently means duplicate notifications when using the GUI: a permanent alert window and a temporary desktop notification.

This should already make notifications much more useful and less annoying. 

Changes which I am considering:

* Always enable error notifications (sync issues and fatal errors) and make file-change notifications optional.
* Let the user select between "file changes", "errors" and "none".

Which one of those options would you prefer?

I am reluctant to add desktop notifications for a lost internet connection. IMO, this is typically communicated by the operating system in some way (such as a system tray icon of its own). Also, when a user deliberately disconnects from the internet they would not want to see a notification.

Likewise for starting the daemon: This can only be properly handled from *outside* the daemon, for instance when invoking a command `maestral start` or running the gui, because the daemon will be started in a separate process. When started by systemd, a failure to start will likely occur before the code to send system notifications has been loaded.

There have been issues on some operating systems with the GUI starting the daemon and I am not quite sure where they come from. Do let me know if you encounter them. But starting via systemd in my experience has never failed.

**Comment by coxackie** [comment]
@SamSchott, many thanks for already stated implementing this. I will try out the dev branch soon - for the time I reverted to 0.5.2 being there was some trouble when it starts under as a `systemd` unit, (which is not there with 0.5.2 - I am using the service files from [here](https://aur.archlinux.org/cgit/aur.git/tree/maestral.service?h=maestral-git)), but maybe I need to get more info to know what is going on.

The way you are proposing to deal with notifications is good and balanced. I think error notifications should not be optional - they are too important to be considered a nuisance (given that they will not be appearing too often). The issue with notifications with remote file changes (which I agree should be optional) is that they may also pile up if, for example, a collaborator is working furiously on a folder and making constant changes. (Again, personal experience.) There is conceptually a better way to deal with them, but I am not sure how implementable this is in the different notification systems: send one persistent notification in terms of file changes within a folder (for example "John Doe changed files in shared folder DoeShared"); then stop sending notifications for changes in the same folder, unless the user closes the previous persistent notification. This is certainly more complicated, but more informative than having notifications off, and more annoying that 117 notifications for remote same-folder changes.

**Comment by SamSchott** [comment]
Yes, I realised too late that there were some issues in the code that keeps systemd informed about the daemon's status. The risk of the pre-release channel :)

The systemd service file looks good to me, it means that maestral is configured as a 'notify' service and that systemd expects regular updates from it or otherwise considers it failed. More details are given in the [wiki](https://github.com/SamSchott/maestral-dropbox/wiki/Systemd-Integration).

The only issue with the file is the `reload` command: According to freedesktop.org for a 'notify' or 'exec' service:

> It is expected that the process configured with ExecStart= is the main process of the service

However, `maestral restart` will spawn a separate process for the daemon and systemd will likely consider the reload failed. You can just leave out this line and let systemd use `ExecStop` and `ExecStrart` instead. 

****

Regarding notifications, is the issue with the notification pop-ups being annoying, or rather the notifications piling up in the 'notification center' history? In the second case, it should be possible to limit the number of notifications shown for maestral. Implementing this on a per-folder basis will be a bit tedious, but one could simply clear old notifications if not already done by the platform itself.

It will require switching from `notify-send` to a dbus implementation on Linux but this should not be difficult.

**Comment by coxackie** [comment]
let me know when the issues with the pre-release have been resolved and I can proceed testing. for the time being I am sticking to 0.5.2, but I can switch and ditch systemd service in the meantime, if you want any feedback.

 regarding notifications: both pop-ups and the pile-up is a bit distracting. Provided you could fix the pile up, you could add an option to temporarily disable notifications. (I recall the official dropbox client had some option like that - for half hour or so.) A way to go for the cli would be to provide a number of notification levels, ranging from "errors only" to "everything". Maybe 3 could be enough (these two, plus a "middle" one). More users should get in this discussion, to understand what the average need is.

 this is coming along very nicely. it clearly has almost all functionality of the official client in linux, but is lighter and uses system libraries instead of everything bundled as dropbox does. the separation of frontend and backend is another huge plus. I believe that, when you feel it has become more stable and towards 1.0, and you advertise this to the right channels (e.g., omg ubuntu), there will be a lot of interest from linux users.

**Comment by SamSchott** [comment]
The issues should be resolved now - I have tested it on Ubuntu and the daemon starts up fine.

Regarding notification levels, I was thinking: 1) file changes, 2) sync issues, 3) fatal errors. But it would indeed be good to get other users' input on this.

I am glad you like the project :) It still has a few kinks to iron out, but hopefully soon it will be sufficiently stable. The input from Github has actually been very helpful eliminating issues.

**Comment by coxackie** [comment]
excellent - I have switched to dev2 and testing. all good till now. the notification levels you suggest make sense.

as I mentioned,  maybe you can add a `snooze` option in notifications; for example, `maestral notifications --snooze 20` could snooze everything (except fatal errors) for 20 minutes. A default of 30 or 60 would make sense, I guess.

**Comment by SamSchott** [comment]
This is implemented in the dev branch now but it will still take some time to be released. v0.6.0 will come with some changes in package structure (a split of gui and daemon into separate packages) which will need to be properly tested. I am also hoping to ship a native Cocoa GUI on macOS with the next release, but this will depend on some bugs in the used libraries to be fixed first...

**Comment by SamSchott** [comment]
If you would like to try it out, feedback on the CLI and GUI would be welcome.

**Comment by coxackie** [comment]
many thanks - 0.6 seems like an exciting release. I cannot really test the new GUI, since I am on Linux. If you create a GTK equivalent I will be happy to take a look. I avoid using the Qt GUI due to poor integration and heavy memory footprint.

**Comment by SamSchott** [comment]
Most of this has been implemented in v0.6.1 (v0.6.0 was never released). The only part which I did not implement is a limit to the number of messages in the notification centre. This would have required adding PyGObject or dbus as a dependency.
