### ISSUE TITLE
Runtime information in .config

### ISSUE THREAD

**Issue by bbaserdem** [SamSchott/maestral-dropbox#86]
I have been running version 0.5.2; on Archlinux.

I noticed that runtime info (such as recent changed folders, etc.) is kept at `~/.config/maestral/maestral.ini`. My understanding is `~/.config` (XDG_CONFIG_HOME) is for static configuration options; like gui and account settings, while `~/.local` (XDG_DATA_HOME) or `~/.cache`(XDG_CACHE_HOME) could be a more appropriate directory for runtime data.

My usecase is my .config is version controlled (which I believe is common); and i cannot include a config file for maestral in version controlling; because the runtime info is dynamic and should not be version controlled.

This is not an issue really; but maybe this behavior can be modified in the future so that the configurations can be shared across machines.

**Comment by SamSchott** [comment]
Yes, I am somewhat abusing the concept of a config file to hold both config and application state information. The reason really is laziness: I already had a good config module from the [Spyder IDE](https://github.com/spyder-ide/spyder) to work with and did not want to write any new code.

Spyder actually does the same but has recently split its config into two files `spyder.ini` and `transient.ini` with the latter containing all the saved state while maintaining a common API to access both. This could potentially solve the issue of version control because you could just ignore the transient file.

Nevertheless, most of the config settings should not be changed manually (as discussed in #61).

The proper approach of course would be to save all state information in `~/Library/Saved Application State` on macOS and possibly XDG_DATA_HOME on Linux. XDG_CACHE_HOME does not seem appropriate because sync state information is essential for Maestral to work and should not be cleared. XDG_DATA_HOME is pretty generic for all user-specific data but should do the job.

**Comment by SamSchott** [comment]
State info has been split off and is now saved in XDG_DATA_HOME in v0.6.1.
