### ISSUE TITLE
How to configure multiple instances on Mac?

### ISSUE THREAD

**Issue by T0mu** [SamSchott/maestral-dropbox#87]
Hi,
I tried to launch multiple instances on mac by calling "/Applications/Maestral.app/Contents/MacOS/main config new" instead of "maestral config new" but while I launched another instance, preferences were the same.
Is it possible to configure multiple profiles on mac?

Thank you
Tom

**Comment by SamSchott** [comment]
Hi Tom, at the moment, this is not possible with the app bundle but only with the Python scripts. This is because the app bundle and the command line interface use different entry points.

You can of course install the Python package on macOS but I can understand that an app bundle is nicer to deal with. I'll have at a look at bundling the CLI together with the app in the next release.

**Comment by SamSchott** [comment]
I have added a command line option `--config-name` or `-c` to the GUI (in release v0.6.1). If the config does not yet exist, it will be automatically created (and eventually deleted when you unlink your account).

**Comment by T0mu** [comment]
Great!
I will test it ASAP!
Many many thanks!

Tomaso


________________________________
Da: SamSchott <notifications@github.com>
Inviato: giovedì 27 febbraio 2020 23:59
A: SamSchott/maestral-dropbox <maestral-dropbox@noreply.github.com>
Cc: T0mu <t.munari@outlook.com>; Author <author@noreply.github.com>
Oggetto: Re: [SamSchott/maestral-dropbox] How to configure multiple instances on Mac? (#87)


I have added a command line option --config-name or -c to the GUI (in release v0.6.1). If the config does not yet exist, it will be automatically created (and eventually deleted when you unlink your account).
